### ISSUE TITLE
Scheduler has invalid cron format

### ISSUE THREAD

**Issue by HollishKid** [Lorenzo0111/ElectionsPlus#24]
On initial load of plugin (no config present in `plugins/`), I get the following start up log: https://pastebin.com/wj9p89Bt (no issues).
I then stop the server with the `stop` command and change `chron.enabled` to `true` in the config.
After starting the server backup, I get the following error start up log (with error): https://pastebin.com/PuLRdMti

I have tried changing the cron expression to the specified `[seconds,minutes,hours,daysOfMonth,months,daysOfWeek,years]` format, but that does not seem to work.

**Comment by Lorenzo0111** [comment]
try setting daysOfWeek to `?`

**Comment by Lorenzo0111** [comment]
More info at: https://www.quartz-scheduler.org/api/2.3.0/index.html

**Comment by Lorenzo0111** [comment]
https://www.quartz-scheduler.org/api/2.3.0/org/quartz/CronExpression.html

**Comment by HollishKid** [comment]
Great! `1 * * * * ? *` appears to work.
This nevertheless means that the default setting (as generated by the first launch of the plugin) is incorrect.

**Comment by Lorenzo0111** [comment]
Fixed for the next update.
